services:
  pgsql:
    image: postgres:17.0
    environment:
      PGPASSWORD: '${PGPASSWORD:-secreted}'
      POSTGRES_USER: '${DB_USER:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_NAME:-proxy}'
    ports:
      - '5432:5432'
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
      - ./pgsql/create-laravel-database.sql:/docker-entrypoint-initdb.d/10-create-laravel-database.sql
      - ./pgsql/create-metabase-database.sql:/docker-entrypoint-initdb.d/20-create-metabase-database.sql
      - ./pgsql/create-sonar-database.sql:/docker-entrypoint-initdb.d/30-create-metabase-database.sql
      - ./pgsql/create-glitchtip-database.sql:/docker-entrypoint-initdb.d/40-create-glitchtip-database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d proxy"]
      interval: 6s
      timeout: 3s
      retries: 5

  mariadb:
    image: mariadb:11.4
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MARIADB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${MARIADB_NAME:-matomo}'
      MYSQL_USER: '${MARIADB_USER:-user}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD:-secret}'
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
    volumes:
      - ./storage/mariadb_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - ./storage/mongo_data:/data/db

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    environment:
      MINIO_ROOT_USER: '${MINIO_USER:-minioadmin}'
      MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD:-minioadmin}'
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-8900}:8900'
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - ./storage/minio_data:/data

  rustfs:
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ADDRESS: '${RUSTFS_ADDRESS:-:9002}'
      RUSTFS_ACCESS_KEY: '${RUSTFS_ACCESS_KEY:-rustfsadmin}'
      RUSTFS_SECRET_KEY: '${RUSTFS_SECRET_KEY:-rustfsadmin}'
      RUSTFS_CONSOLE_ENABLE: '${RUSTFS_CONSOLE_ENABLE:-true}'
      RUSTFS_CONSOLE_ADDRESS: '${RUSTFS_CONSOLE_ADDRESS:-:9003}'
      RUSTFS_SERVER_DOMAINS: '${RUSTFS_SERVER_DOMAINS:-localhost}'
    ports:
      - '${RUSTFS_PORT:-9002}:9002'
      - '${RUSTFS_CONSOLE_PORT:-9003}:9003'
    volumes:
      - ./storage/rustfs_data:/data
    command: /data

  camunda:
    image: camunda/camunda-bpm-platform:7.23.0
    ports:
      - '${CAMUNDA_PORT:-8080}:8080'
    depends_on:
      pgsql:
        condition: service_healthy
    links:
      - pgsql
    environment:
      TZ: Asia/Jakarta
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://pgsql:5432/camunda
      DB_USERNAME: '${DB_USER:-user}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - ./storage/camunda_data:/camunda
      - ./storage/camunda_invoice:/camunda/webapps/camunda-invoice

  matomo:
    image: matomo:latest
    ports:
      - '${MATOMO_PORT:-8081}:80'
    environment:
      MATOMO_DATABASE_HOST: mariadb
      MATOMO_DATABASE_ADAPTER: MYSQLI
      MATOMO_DATABASE_SCHEMA: Mariadb
      MATOMO_DATABASE_USERNAME: '${DB_USER:-user}'
      MATOMO_DATABASE_PASSWORD: '${DB_PASSWORD:-secret}'
      MATOMO_DATABASE_DBNAME: matomo
    volumes:
      - ./storage/matomo_data:/var/www/html:z'
    depends_on:
      mariadb:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '${MAIL_SERVER_PORT:-1025}:1025'
      - '${MAIL_ADMIN_PORT:-8025}:8025'

  metabase:
    platform: linux/amd64
    image: metabase/metabase:latest
    ports:
      - '${METABASE_PORT:-3000}:3000'
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USER:-user}
      MB_DB_PASS: '${DB_PASSWORD:-secret}'
      MB_DB_HOST: pgsql
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ./storage/metabase_data:/metabase-data

  sonar:
    image: sonarqube:25.11.0.114957-community
    depends_on:
      pgsql:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://pgsql:5432/sonar
      SONAR_JDBC_USERNAME: '${DB_USER:-user}'
      SONAR_JDBC_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${SONAR_PORT:-9001}:9000'

  jasper:
    image: bitnami/jasperreports:7-debian-10
    ports:
      - "${JASPER_PORT:-8082}:8080"
    environment:
      MARIADB_HOST: 'mariadb'
      MARIADB_PORT_NUMBER: '3306'
      JASPERREPORTS_DATABASE_USER: 'root'
      JASPERREPORTS_DATABASE_PASSWORD: '${MARIADB_PASSWORD:-secret}'
      JASPERREPORTS_DATABASE_NAME: 'jasper'
      JASPERREPORTS_USERNAME: 'user'
      JASPERREPORTS_PASSWORD: 'secret'
    volumes:
      - ./storage/jasperreports_data:/bitname
    depends_on:
      - mariadb

  sso:
    image: keycloak/keycloak:25.0
    command: start
    environment:
      KC_HOSTNAME: 192.168.68.116
      KC_HOSTNAME_PORT: "${KEYCLOAK_PORT:-8083}"
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-secret}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pgsql/${POSTGRES_DB:-sso}
      KC_DB_USERNAME: '${DB_USER:-user}'
      KC_DB_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${KEYCLOAK_PORT:-8083}:8080'
    depends_on:
      - pgsql

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DB_POSTGRES_HOST: '${DB_HOST:-pgsql}'
      DB_POSTGRES_PORT: '${DB_PORT:-5432}'
      DB_POSTGRES_USER: '${DB_USER:-user}'
      DB_POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      DB_POSTGRES_NAME: '${DB_NAME:-proxy}'
      INITIAL_ADMIN_EMAIL: '${PROXY_USER:-root@proxy.test}'
      INITIAL_ADMIN_PASSWORD: '${PROXY_PASSWORD:-p@ssW0rd}'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    depends_on:
      - pgsql
    volumes:
      - ./storage/proxy_data:/data
      - ./storage/proxy_letsencrypt:/etc/letsencrypt

  # GlitchTip's dedicated Redis service
  glitchtip-redis:
    image: valkey/valkey
    restart: unless-stopped
    volumes:
      - ./storage/glitchtip_redis_data:/data
    ports:
      - "${GLITCHTIP_REDIS_PORT:-6380}:6379"

  # GlitchTip services
  glitchtip-web:
    image: glitchtip/glitchtip
    depends_on:
      - pgsql
      - glitchtip-redis
    ports:
      - "${GLITCHTIP_PORT:-8084}:8000"
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-secret}@pgsql:5432/${GLITCHTIP_DB:-glitchtip}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY:-change_me_to_something_random}
      PORT: 8000
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL:-consolemail://}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN:-https://glitchtip.example.com}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL:-email@example.com}
      CELERY_WORKER_AUTOSCALE: "1,3"
      REDIS_URL: redis://glitchtip-redis:6379/0
    restart: unless-stopped
    volumes:
      - ./storage/glitchtip_uploads:/code/uploads

  glitchtip-worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - pgsql
      - glitchtip-redis
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-secret}@pgsql:5432/${GLITCHTIP_DB:-glitchtip}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY:-change_me_to_something_random}
      PORT: 8000
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL:-consolemail://}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN:-https://glitchtip.example.com}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL:-email@example.com}
      CELERY_WORKER_AUTOSCALE: "1,3"
      REDIS_URL: redis://glitchtip-redis:6379/0
    restart: unless-stopped
    volumes:
      - ./storage/glitchtip_uploads:/code/uploads

  glitchtip-migrate:
    image: glitchtip/glitchtip
    depends_on:
      - pgsql
      - glitchtip-redis
    command: ./bin/run-migrate.sh
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-secret}@pgsql:5432/${GLITCHTIP_DB:-glitchtip}
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY:-change_me_to_something_random}
      PORT: 8000
      EMAIL_URL: ${GLITCHTIP_EMAIL_URL:-consolemail://}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN:-https://glitchtip.example.com}
      DEFAULT_FROM_EMAIL: ${GLITCHTIP_FROM_EMAIL:-email@example.com}
      CELERY_WORKER_AUTOSCALE: "1,3"
      REDIS_URL: redis://glitchtip-redis:6379/0

volumes:
  glitchtip_uploads:
